### ISSUE TITLE
Test Renogy 48v battery compatibility

### ISSUE THREAD

**Issue by cyrils** [cyrils/renogy-bt#21]
Test compatibility of Renogy Battery [RBT50LFP48S](https://www.renogy.com/support/downloads/batteries/lithium-batteries/48v-50ah-smart-lithium-iron-phosphate-battery-rbt50lfp48s.html)

**Comment by jimmystewpot** [comment]
I have one of these batteries, I am currently working on getting it to work.

**Comment by cyrils** [comment]
Sure, let me know how that goes. Here is the register mapping if you need [Lithium.Iron.Battery.BMS.Modbus.Protocol.V1.7.zh-CN.en.1.pdf](https://github.com/cyrils/renogy-bt/files/12444500/Lithium.Iron.Battery.BMS.Modbus.Protocol.V1.7.zh-CN.en.1.pdf)

**Comment by cyrils** [comment]
@jimmystewpot Any luck?

**Comment by jimmystewpot** [comment]
@cyrils no success  yet, but I am working on it when I have spare time.

**Comment by cyrils** [comment]
Sure. If you can share the hex output may be I can also help.  In BaseClient#61
```py
logging.info(f"on_data_received: response for read operation{response.hex()}")
```
