### ISSUE TITLE
ERROR:root:base client cannot be used directly

### ISSUE THREAD

**Issue by riker65** [cyrils/renogy-bt#48]
Hi 
I am runnng into the error 

**ERROR:root:base client cannot be used directly**
`
INFO:root:[E0:7D:EA:83:xx:xx] Resolved services

INFO:root:subscribed to notification 0000fff1-0000-1000-8000-00805f9b34fb
INFO:root:found write characteristic 0000ffd1-0000-1000-8000-00805f9b34fb
INFO:root:resolved services

ERROR:root:base client cannot be used directly

INFO:root:characteristic_enable_notifications_succeeded
`

any root cause known?

what am I missing

thanks a lot

**Comment by cyrils** [comment]
Your config.ini is probably messed up. Can you upload it here?

**Comment by riker65** [comment]
Hi 
looks like device was frozen,
after repowering the renogy it worked.

thanks a lot
