### ISSUE TITLE
install steps

### ISSUE THREAD

**Issue by theboss0539** [cyrils/renogy-bt#50]
hey i have been unable to get this to funtion on my pi zero i cant complet the config

**Comment by theboss0539** [comment]
pi@raspberrypi:~ $ python3 ./example.py <config.ini>
-bash: syntax error near unexpected token `newline'
this is the error

**Comment by cyrils** [comment]
Command is ` python3 ./example.py config.ini`

**Comment by theboss0539** [comment]
DEBUG:root:create_request_payload 5000 => [255, 3, 19, 136, 0, 17, 20, 182]
INFO:root:characteristic_enable_notifications_succeeded
INFO:root:characteristic_write_value_succeeded
WARNING:root:on_data_received: unknown operation=0
WARNING:root:on_data_received: unknown operation=0
 this is now what i get and i am using the bt 2 and 4 48v [RBT50LFP48S](https://www.renogy.com/support/downloads/batteries/lithium-batteries/48v-50ah-smart-lithium-iron-phosphate-battery-rbt50lfp48s.html)

**Comment by theboss0539** [comment]
hey i have my pi reading info form bt 2 it seems like only one of 4 battery's but i cant get it to out put to PVoutput and i feel like i am missing some step just not sure where also is the a way to only display battey voltage and cappacity not voltage of each cell

**Comment by cyrils** [comment]
You need separate config.ini for each battery, check documentation. Yes you can filter fields, there is `fields` option in config.
