### ISSUE TITLE
tested also with RCC40RVRE

### ISSUE THREAD

**Issue by riker65** [cyrils/renogy-bt#52]
Hi

thanks for your software
working also for SKU: RCC40RVRE
and bT-2

Looks like ony BT-2 is connect device ID is set to 17. at least for mine.

you might want to add this to the documentation

https://de.renogy.com/rover-elite-40a-mppt-solar-laderegler/?Rng_ads=47c6186493f92f11&kw=&ad=&gr=&ca=20102189424&pl=ga&gclid=CjwKCAiAhJWsBhAaEiwAmrNyq7c3CPUWpBW4moMmLoi2a6Q2RNQs4UG8Z7rKWTAH6MdfN2SsMZducxoClbkQAvD_BwE&r_u_id=7813406497&gad_source=1

**Comment by riker65** [comment]
Stand alone

**Comment by cyrils** [comment]
So that broadcast address 255 doesn't work?

**Comment by riker65** [comment]
No
I experiences once BT-2 was connected Device ID changed to 17 in my case.
