### ISSUE TITLE
ML2440

### ISSUE THREAD

**Issue by FrancineMatos** [cyrils/renogy-bt#55]
Just to confirm it's working on ML2440 with BT-1
![image](https://github.com/cyrils/renogy-bt/assets/148077119/0fa4359d-54e0-4fd8-938e-7bc93564759e)

**Comment by FrancineMatos** [comment]
Just to clarify a thing i have to add 2 spaces after the alias of the bluethoot device in the config.ini to work.

Like this: "BT-TH-73C8EA91  "

**Comment by FrancineMatos** [comment]
Everything workin wiuth MQTT integrated to HA.

![image](https://github.com/cyrils/renogy-bt/assets/148077119/5dc84d7c-b8f9-4d9d-8acc-cc7411e10768)

**Comment by cyrils** [comment]
Great! I'll add it to the doc.

> Just to clarify a thing i have to add 2 spaces after the alias of the bluethoot device in the config.ini to work.

Thats strange as it matches either the mac adress or alias. Are you sure your mac addr is correct in the config?

**Comment by FrancineMatos** [comment]
> Great! I'll add it to the doc.
> 
> > Just to clarify a thing i have to add 2 spaces after the alias of the bluethoot device in the config.ini to work.
> 
> Thats strange as it matches either the mac adress or alias. Are you sure your mac addr is correct in the config?

Yes If try to connect without the 2 spaces it's says that the device was not found even If the Mac is correct. I belive that the device broadcast the alias with those spaces.

**Comment by cyrils** [comment]
I pushed a change, hopefully it fixed the alias issue.

**Comment by FrancineMatos** [comment]
> I pushed a change, hopefully it fixed the alias issue.

Thanks, now the device was found without the spaces in the alias. Even looks like that it's imprrove the connection with the device, some times it took a while to connect and start to send information, but now it's connecting very fast.
