### ISSUE TITLE
Temperature showing up as hotter than surface of the sun.

### ISSUE THREAD

**Issue by Anglac** [cyrils/renogy-bt#60]
My battery temperatures have been reporting at 11,000+ degrees f, given the lack of fires I believe this to be false.

I think the issue is that the battery temperature returns a signed int, and it's being handled as if it's unsigned.

switching line 37 of BatteryClient.py to 

            celcius = bytes_to_int(bs, 5 + i*2, 2, scale = 0.1, signed=True)

seems to have it reporting more reasonable temperatures.

**Comment by cyrils** [comment]
@Anglac What are the values you see when adding signed flag?

**Comment by Anglac** [comment]
Started getting below freezing (sub 32f or 0c) temperatures after adding the signed flag.
(below freezing is expected values in my area in the winter time)

Before the change was getting things like 11826.68f or 6552.6c (which was suspiciously close to 65,535 limit for unsigned 16 bit int when scaled by 0.1).

**Comment by cyrils** [comment]
Fixed in master
