### ISSUE TITLE
RICH SOLAR 60

### ISSUE THREAD

**Issue by morcant** [cyrils/renogy-bt#64]
Confirmed working with Rich Solar 60 and Rich Solar labeled BT-1:

{'function': 'READ', 'model': 'ML4860N15', 'device_id': 1, 'battery_percentage': 100, 'battery_voltage': 13.6, 'battery_current': 16.94, 'battery_temperature': 93.2, 'controller_temperature': 107.6, 'load_status': 'off', 'load_voltage': 0.0, 'load_current': 0.0, 'load_power': 0, 'pv_voltage': 55.6, 'pv_current': 4.31, 'pv_power': 240, 'max_charging_power_today': 303, 'max_discharging_power_today': 0, 'charging_amp_hours_today': 18, 'discharging_amp_hours_today': 0, 'power_generation_today': 254, 'power_consumption_today': 0, 'power_generation_total': 54642, 'charging_status': 'mppt', 'battery_type': 'lithium', '__device': 'BT-TH-73C4AA5D', '__client': 'RoverClient'}

**Comment by cyrils** [comment]
Thanks
