### ISSUE TITLE
How to run 2 config files ?

### ISSUE THREAD

**Issue by conor-o-brien** [cyrils/renogy-bt#68]
Hi, Is it possible to run 2 config files at same time and if so, how?
I can run them both individually config1.ini and config.ini
The reason I have to do this is because I am using both Bt1 and Bt2 devices.

**Comment by cyrils** [comment]
Not sure what you meant by at the same time. You will need separate config file for each device, but you can run them back to back or at the same time. Ex: create a sh file with
```sh
python3 example.py config1.ini 
python3 example.py config2.ini 
```

**Comment by conor-o-brien** [comment]
Thanks

> Not sure what you meant by at the same time. You will need separate config file for each device, but you can run them back to back or at the same time. Ex: create a sh file with
> 
> ```shell
> python3 example.py config1.ini 
> python3 example.py config2.ini 
> ```

Thanks, I got that working when adding to crontab.

**Comment by conor-o-brien** [comment]
> Not sure what you meant by at the same time. You will need separate config file for each device, but you can run them back to back or at the same time. Ex: create a sh file with
> 
> ```shell
> python3 example.py config1.ini 
> python3 example.py config2.ini 
> ```


Thanks, I got that working when adding to crontab
