### ISSUE TITLE
Writing to BT1

### ISSUE THREAD

**Issue by jbonja** [cyrils/renogy-bt#69]
I have the system running on my RPI4 and its tied into Node Red.  Ultimate goal is a "wireless" weather station for my dad.  BTW Thanks for this.

Looking to see if anyone has worked with the code to specifically control the load power? I want to sense the battery level, send a last gasp email to me before it goes down and then shut down PI and power before I drain bat to zero.

I see the modbus document talks about it but didn't see any specific write functions in the code.

**Comment by cyrils** [comment]
Load control is already supported. Check `RoverClient.set_load()`. Be careful not to go into a calback loop, as even the write operation will trigger `on_data_received`.
