### ISSUE TITLE
Renogy config setting write 

### ISSUE THREAD

**Issue by riker65** [cyrils/renogy-bt#79]
Hi
wondering if you tried to change the settings via BLE like 
custom setting for Charging or system etc.

Thanks t

**Comment by cyrils** [comment]
This library currently doesn't support settings update. However its technically possible, the specs are available in [ROVER.MODBUS.pdf](https://github.com/cyrils/renogy-bt/files/12787920/ROVER.MODBUS.pdf), if you are familiar with python.

**Comment by riker65** [comment]
Unfortunately I am a python dummy
